FORMAT: 1A
HOST: http://shrub.apiblueprint.org/

# shrub

shrub is a web app that checks customer's service info then connects them to a chat bot

## Customers [/customers:id]

### Get By Service number [GET]

+ Response 200 (text/plain)
    
+ Response 404 (text/plain)