const SUBMIT_SERVICE_NUMBER = 'SUBMIT_SERVICE_NUMBER';
const CHECK_SERVICE_NUMBER = 'CHECK_SERVICE_NUMBER';
const CUSTOMER_FOUND = 'CUSTOMER_FOUND';
const INVALID_SERVICE_NUMBER = 'INVALID_SERVICE_NUMBER';
const ERROR = 'ERROR';
const CHECK_PHONE_NUMBER = 'CHECK_PHONE_NUMBER';
const PHONE_NUMBER_VERIFIED = 'PHONE_NUMBER_VERIFIED';
const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';

export { SUBMIT_SERVICE_NUMBER, CHECK_SERVICE_NUMBER, CUSTOMER_FOUND, INVALID_SERVICE_NUMBER, INVALID_PHONE_NUMBER, PHONE_NUMBER_VERIFIED, CHECK_PHONE_NUMBER, ERROR };