const SUBMIT_SERVICE_NUMBER = 'SUBMIT_SERVICE_NUMBER';
const CHECK_SERVICE_NUMBER = 'CHECK_SERVICE_NUMBER';
const CUSTOMER_FOUND = 'CUSTOMER_FOUND';
const INVALID_SERVICE_NUMBER = 'INVALID_SERVICE_NUMBER';

export { SUBMIT_SERVICE_NUMBER, CHECK_SERVICE_NUMBER, CUSTOMER_FOUND, INVALID_SERVICE_NUMBER };